export const BUILTIN_CHALLENGES = [
  {
    id: "challenge_mindfulness30",
    title: "30-Day Mindfulness",
    description: "Complete at least one mindfulness activity every day for 30 days.",
    category: "Mindfulness",
    difficulty: "Beginner",
    totalDays: 30,
    xpReward: 150,
    activityType: "timer",
  },
  {
    id: "challenge_gratitudeweek",
    title: "Gratitude Week",
    description: "Write 3 things you're grateful for every day for 7 days.",
    category: "Journaling",
    difficulty: "Beginner",
    totalDays: 7,
    xpReward: 60,
    activityType: "gratitude",
  },
  {
    id: "challenge_sleepsprint",
    title: "Sleep Hygiene Sprint",
    description: "Check in on your wind-down routine for 14 consecutive nights.",
    category: "Sleep",
    difficulty: "Moderate",
    totalDays: 14,
    xpReward: 90,
    activityType: "checkin",
  },
  {
    id: "challenge_connector",
    title: "Community Connector",
    description: "Post in a support group discussion, then confirm you've shared with the community.",
    category: "Community",
    difficulty: "Beginner",
    totalDays: 3,
    xpReward: 40,
    activityType: "generic",
  },
];
