export const BUILTIN_MISSIONS = [
  // ── TODAY'S 5 ──────────────────────────────────────────────────────────────
  {
    id: "default_breathing",
    title: "4-7-8 Breathing",
    description: "Complete two rounds of 4-7-8 breathing to activate your parasympathetic nervous system and reduce stress.",
    category: "breathing" as const,
    duration: 5,
    xp: 10,
    recurring: true,
    activityType: "breathing" as const,
    completed: false,
  },
  {
    id: "default_journal",
    title: "Daily Gratitude Entry",
    description: "Write down three things you're grateful for today — no matter how small. Builds a positive thinking habit.",
    category: "journaling" as const,
    duration: 5,
    xp: 15,
    recurring: true,
    activityType: "gratitude" as const,
    completed: false,
  },
  {
    id: "default_meditation",
    title: "Morning Mindfulness",
    description: "Spend 10 minutes in guided breath-awareness meditation to start your day with clarity and calm.",
    category: "mindfulness" as const,
    duration: 10,
    xp: 25,
    recurring: true,
    activityType: "timer" as const,
    completed: false,
  },
  {
    id: "default_walk",
    title: "Mindful Walk",
    description: "Take a 15-minute walk outside. Notice 5 things you see, 4 you hear, 3 you can touch — a grounding exercise.",
    category: "movement" as const,
    duration: 15,
    xp: 20,
    recurring: true,
    activityType: "walk" as const,
    completed: false,
  },
  {
    id: "default_checkin",
    title: "Evening Check-in",
    description: "Answer one reflection question: What challenged me today and how did I respond? Write freely for 5 minutes.",
    category: "journaling" as const,
    duration: 5,
    xp: 15,
    recurring: true,
    activityType: "reflection" as const,
    completed: false,
  },
  // ── UPCOMING 15 ────────────────────────────────────────────────────────────
  {
    id: "default_bodyscan",
    title: "Body Scan Meditation",
    description: "Slowly scan from head to toe, noticing sensations without judgment. Helps release tension you didn't know you were holding.",
    category: "mindfulness" as const,
    duration: 15,
    xp: 20,
    recurring: true,
    activityType: "bodyscan" as const,
    completed: false,
  },
  {
    id: "default_affirmations",
    title: "Daily Affirmations",
    description: "Read three affirmations aloud in front of a mirror. Choose ones that challenge your self-critical inner voice.",
    category: "habit" as const,
    duration: 5,
    xp: 10,
    recurring: true,
    activityType: "generic" as const,
    completed: false,
  },
  {
    id: "default_stretch",
    title: "Morning Stretch Routine",
    description: "10 minutes of gentle neck rolls, shoulder shrugs, and forward folds to release overnight tension from your body.",
    category: "movement" as const,
    duration: 10,
    xp: 15,
    recurring: true,
    activityType: "stretch" as const,
    completed: false,
  },
  {
    id: "default_grounding",
    title: "5-4-3-2-1 Grounding",
    description: "Name 5 things you see, 4 you hear, 3 you can touch, 2 you smell, 1 you taste. Anchors you to the present moment instantly.",
    category: "mindfulness" as const,
    duration: 5,
    xp: 10,
    recurring: true,
    activityType: "walk" as const,
    completed: false,
  },
  {
    id: "default_social",
    title: "Reach Out to Someone",
    description: "Send a genuine message to a friend or family member. Social connection is one of the strongest predictors of wellbeing.",
    category: "social" as const,
    duration: 15,
    xp: 25,
    recurring: false,
    activityType: "social" as const,
    completed: false,
  },
  {
    id: "default_progressive",
    title: "Progressive Muscle Relaxation",
    description: "Tense and release each muscle group from feet to face. 15 minutes that dramatically reduce physical anxiety symptoms.",
    category: "breathing" as const,
    duration: 15,
    xp: 20,
    recurring: true,
    activityType: "bodyscan" as const,
    completed: false,
  },
  {
    id: "default_worry",
    title: "Worry Dump Journal",
    description: "Write every worry on your mind without filtering. Then review: which are in your control? Focus only on those.",
    category: "journaling" as const,
    duration: 10,
    xp: 15,
    recurring: true,
    activityType: "worry" as const,
    completed: false,
  },
  {
    id: "default_screen",
    title: "Tech-Free Break",
    description: "Step away from all screens for 30 minutes. Read, draw, stretch, or sit in silence. Your brain needs unstructured rest.",
    category: "habit" as const,
    duration: 30,
    xp: 30,
    recurring: true,
    activityType: "timer" as const,
    completed: false,
  },
  {
    id: "default_hydration",
    title: "Mindful Hydration",
    description: "Drink a full glass of water slowly, focusing on the sensation. Hydration directly impacts mood and cognitive function.",
    category: "habit" as const,
    duration: 5,
    xp: 5,
    recurring: true,
    activityType: "generic" as const,
    completed: false,
  },
  {
    id: "default_selfcompassion",
    title: "Self-Compassion Moment",
    description: "Write one paragraph treating yourself as you'd treat a struggling friend. Counter self-criticism with kindness.",
    category: "journaling" as const,
    duration: 10,
    xp: 20,
    recurring: true,
    activityType: "self_compassion" as const,
    completed: false,
  },
  {
    id: "default_creative",
    title: "Creative Expression",
    description: "Spend 20 minutes drawing, colouring, writing poetry, or playing music — anything creative with no goal or judgment.",
    category: "habit" as const,
    duration: 20,
    xp: 25,
    recurring: false,
    activityType: "generic" as const,
    completed: false,
  },
  {
    id: "default_nature",
    title: "Connect with Nature",
    description: "Sit outside for 20 minutes without your phone. Observe the sky, plants, or animals. Natural settings lower cortisol.",
    category: "movement" as const,
    duration: 20,
    xp: 20,
    recurring: true,
    activityType: "timer" as const,
    completed: false,
  },
  {
    id: "default_strength",
    title: "Positive Strengths List",
    description: "Write 5 personal strengths or recent wins. Regularly recognizing competence builds resilience over time.",
    category: "journaling" as const,
    duration: 5,
    xp: 15,
    recurring: true,
    activityType: "strength" as const,
    completed: false,
  },
  {
    id: "default_sleep",
    title: "Sleep Hygiene Wind-Down",
    description: "30 minutes before bed: dim lights, stop screens, do gentle stretching or light reading to signal your body it's time to rest.",
    category: "habit" as const,
    duration: 30,
    xp: 20,
    recurring: true,
    activityType: "timer" as const,
    completed: false,
  },
  {
    id: "default_values",
    title: "Values Reflection",
    description: "Name one core value important to you and write one sentence about how you will honor it in today's actions.",
    category: "journaling" as const,
    duration: 10,
    xp: 20,
    recurring: true,
    activityType: "values" as const,
    completed: false,
  },
];

export const BUILTIN_DAILY_LIMIT = 5;
